### PR TITLE
Various fixes by JMartinez9820

### PR DESCRIPTION
**Pull request by JMartinez9820**
Some issues that I have fixed here. Fixed the Silenced Pistol and adjusted the offsets of the Super GL pickup sprite,

### CODE REVIEW

**Comment by tunbridgep** [comment]
I have reviewed your changes, and I like the bugfixes. Before I merge, I have a few quick questions and there are a couple of minor issues.

Firstly, I don't understand the need to add a new PNG file and then delete the old lump. I get that this works, which is great, but the PB guys are very strict about pull requests (and rightly so), so they would likely prefer if you offset the existing lump rather than creating a new one, however in either case it's not likely to result in compatibility issues, but the PB guys might not like it.

Secondly, the diff of your pistol changes shows the entire file in RED, then the entire file in GREEN again. This means you have modified the file in such a way that the entire file is one big chunk. This is bad for compatibility as it means any other changes to the pistol will cause merge conflicts. I use SourceTree for all my github management and it shows me the contents of every chunk I wish to commit, which will likely help you diagnose what's causing this issue. I suspect it has something to do with your line endings. You can get more information [here](https://stackoverflow.com/questions/19593909/git-diff-sees-whole-file-as-changed-when-its-not).

Lastly, I think having an "open slide" picture for the pistol when empty (for both silenced and unsilenced versions as well as dual-wield versions) might be a good idea and may be what the developers originally intended, but that's totally optional and up to you. It's also possible that the pistol will be revamped like all the other weapons, so your fix might be seen as "unnecessary". You will have to ask the devs about that one. Either way, fixing existing bugs is good, even if they are eventually going to be replaced, and makes the game more playable for everyone who is using the current github build of the mod, so I wholeheartedly support doing these kinds of fixes, and will be more than happy to merge them in with mine once the outstanding issues are fixed.

**Comment by JMartinez9820** [comment]
Closed PR because after I read this, I noticed it may not be a good idea. Deleting fork because of this. I'm very sorry for the inconvenience. I have a beginner's experience of Github, I learned it recently in college.

**Comment by JMartinez9820** [comment]
I feel like killing myself every time I make a mistake. Idk why

**Comment by tunbridgep** [comment]
I made the same mistakes with my first PB commit, and it's a good way to
learn. You're eager to contribute and that's a good thing. Even though you
might feel bad, the feeling you get when your changes are accepted are
worth it.

I promise if you remake the fork and do the changes again, you'll feel like
it's worth it. And PB does better with every developer, especially since
most people are only interested in adding features, not fixing bugs. You're
obviously interested in games, and this is a perfect area to learn version
control. Standards for code are usually high, but don't take it personally
if your change is rejected - it's not a reflection on you personally, and
everyone makes mistakes. Your actual code is fine, it's just niggling
configuration issues which means once they are figured out, you'll go far.
I hadn't contributed to any projects before this either and I learnt a lot
doing it.

It would be good to have more people like you around in the community, and
I'm sure you'll find most people here accepting of newer people, especially
compared to a professional project where jobs and money are on the line.

I hope you'll reconsider your request to abandon the project. Even if you
decide to simply playtest and log issues on the PB issues page, it'll be
useful.

**Comment by JMartinez9820** [comment]
Remade a new PR and fork

**Comment by tunbridgep** [comment]
That's good to hear

**Pull request closed without merging**
